Add E2E Tests
open-dollar/arbitrum-vault-saviour pull request #9
Opened 2024-05-17 16:27 UTC by daopunk

E2E Tests
- fuzz test saviour saveSafe
- fuzz access control tests
- liquidation tests
- math tests

ODSaviour
- changes to calculations in saveSafe

2024-05-21 17:29 UTC, pi0neerpat requested changes
fix failing tests
- `test_algorithm`
- `test_liquidateUnprotectedSafe`

2024-05-22 00:15 UTC, pi0neerpat requested changes

2024-05-22 00:15 UTC, pi0neerpat commented on src/contracts/ODSaviour.sol
> +      if (_newCollatXliqPrice <= _debtXaccumuRate) revert SafetyRatioNotMet();
rename 
- `_reqCollateral` to `_requiredCollateral` 
- `_collateralXliqPrice` to `_collateralXliquidationPrice`
- `_debtXaccumuRate` to `_debtXaccumulatedRate`
- `_newCollatXliqPrice` to `_newCollateralXliquidationPrice`

2024-05-22 17:50 UTC, pi0neerpat commented
Add logs to show math output during algorithm test

2024-05-22 17:50 UTC, pi0neerpat commented on src/contracts/ODSaviour.sol
> +      if (_newCollatXliqPrice <= _debtXaccumuRate) revert SafetyRatioNotMet();
Also change in the tests

2024-05-22 21:24 UTC, daopunk commented
> Add logs to show math output during algorithm test

logs added, but for more in-depth look, run 
`forge t --match-test test_liquidateProtectedSafe -vvvv`

2024-05-23 17:34 UTC, pi0neerpat approved these changes

2024-05-23 17:35 UTC, merged